### ISSUE TITLE
Translation: post-workshop/post-workshop-ja.md

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/assessment-archives#2]
Translation: `post-workshop/post-workshop-ja.md`
-----

* Please translate the content [of this file](https://github.com/swcarpentry-ja/assessment-archives/blob/master/post-workshop/post-workshop-ja.md) into Japanese.
* Please add a comment to the issue **before** you start translating, so other people know that you are translating.
* It is fine to comment that you will translate part of the file (it is not necessary to translate it all at once).
* Once you have finished translating, send a pull request and reference this issue.

-----
* [このフィアる](https://github.com/swcarpentry-ja/assessment-archives/blob/master/post-workshop/post-workshop-ja.md)の内容を日本語に翻訳してください。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**このイシューにコメントを書いてください。
* コメントでこのファイルの一部を翻訳しますと書いても大丈夫です（全部一気に翻訳する必要はありません）。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

**Comment by naganeayu** [comment]
I will work on this 😉

**Comment by joelnitta** [comment]
Great, thank you very much!
